package com.fndt.alarm.domain.utils

import com.fndt.alarm.BuildConfig

const val FIVE_MINUTES = 5

const val INTENT_FIRE_ALARM = "${BuildConfig.APPLICATION_ID}.FIRE_ALARM"
const val INTENT_STOP_ALARM = "${BuildConfig.APPLICATION_ID}.STOP_ALARM"
const val INTENT_SNOOZE_ALARM = "${BuildConfig.APPLICATION_ID}.SNOOZE_ALARM"

//REPEAT PERIOD CODES
const val REPEAT_SUNDAY: Byte = 0b1000000
const val REPEAT_MONDAY: Byte = 0b0100000
const val REPEAT_TUESDAY: Byte = 0b0010000
const val REPEAT_WEDNESDAY: Byte = 0b0001000
const val REPEAT_THURSDAY: Byte = 0b0000100
const val REPEAT_FRIDAY: Byte = 0b0000010
const val REPEAT_SATURDAY: Byte = 0b0000001
const val REPEAT_NONE: Byte = 0b0000000
const val REPEAT_ONCE_DESTROY: Byte = -0b0000001
val REPEATS_LIST = listOf(
    REPEAT_MONDAY, REPEAT_TUESDAY, REPEAT_WEDNESDAY, REPEAT_THURSDAY, REPEAT_FRIDAY,
    REPEAT_SATURDAY, REPEAT_SUNDAY, REPEAT_ONCE_DESTROY
)